
export const iconFactory: Record<string, any> = {
    accountCheck: "account-check",
    accountEdit: "account-edit",
    accountCancel: "account-cancel",
    arrowUp: "chevron-up",
    arrowRight: "chevron-right",
    arrowLeft: "chevron-left",
    arrowDown: "chevron-down",
    accounting: "accounting",
    ads: "ads",
    booking: "booking",
    card: "card",
    calendar: "calendar",
    coffee: "coffee",
    customerInfo: "customer-info",
    checking: "checking",
    clear: "close",
    close: "close",
    customer: "customer",
    dashboard: "dashboard",
    document: "document",
    dotsVertical: "dots-vertical",
    events: "events",
    email: "email",
    pencil: "pencil",
    grid: "view-grid",
    holidays: "holidays",
    menu: "menu",
    incidents: "incidents",
    logout: "logout",
    list: "view-list",
    message: "message",
    maintenance: "maintenance",
    notification: "notification",
    pickerIconPrev: "chevron-left",
    pickerIconNext: "chevron-right",
    providers: "providers",
    phone: "phone",
    replacements: "replacements",
    reports: "reports",
    remuneration: "remuneration",
    roles: {
        instructor: 'instructor',
        roomInstructor: 'room-instructor',
        personalTrainer: 'personal-trainer',
        customerService: 'phone-msg',
        coordination: 'table-check',
        administration: 'mouse',
        directorate: 'direction',
        cleaning: 'cleaning',
        maintenance: 'maintenance',
        operations: 'operations',
        reception: 'reception',
        humanResources: 'human-resources',
        supervisor: 'admin',
    },
    schedule: "schedule",
    scheduleTimeslot: "schedule-timeslot",
    sessions: "sessions",
    staff: "staff",
    search: "search",
    sendEmail: "send-email",
    trash: "trash",
    wallet: "wallet",

}

export default defineNuxtPlugin(() => {
    return {
        provide: {
            icon: iconFactory
        }
    }
})